// 33 Node Process Tree Data - Mapped from Sequence Diagram
// Based on: docs/PROOF_OF_AUTHENTICITY_PIPELINE_SEQUENCE.md

export type ServiceType = 'walrus' | 'seal' | 'sui' | 'ai' | 'reverse-search' | 'queue' | 'gateway' | 'aggregator';
export type NodeType = 'root' | 'parallel' | 'sequential' | 'merge' | 'service-call';
export type NodeStatus = 'pending' | 'active' | 'processing' | 'completed' | 'failed';

export interface TreeNode {
  id: string;
  name: string;
  icon: string;
  description: string;
  service?: ServiceType;
  stage: number;
  substage?: string;
  type: NodeType;
  enclaveId?: 1 | 2 | 3;
  position: { x: number; y: number; z: number };
  children: string[];
  color: string;
  estimatedTime: string;
}

export interface TreeConnection {
  id: string;
  from: string;
  to: string;
  type: 'vertical' | 'horizontal' | 'diagonal';
}

// Service-specific colors (matching theme)
export const SERVICE_COLORS = {
  walrus: '#3B82F6',      // blue-500
  seal: '#A855F7',        // purple-500
  sui: '#06B6D4',         // cyan-500
  ai: '#10B981',          // green-500
  'reverse-search': '#F59E0B', // orange-500
  queue: '#6366F1',       // indigo-500
  gateway: '#8B5CF6',     // violet-500
  aggregator: '#EC4899',  // pink-500
} as const;

// All 33 nodes mapped from sequence diagram
// Scaled for 900px width: x positions from 50-850, y with better spacing
export const TREE_NODES: TreeNode[] = [
  // ===== STAGE 1: Upload & Storage (4 nodes) =====
  {
    id: 'node-1',
    name: 'User Upload',
    icon: '📤',
    description: 'Client uploads encrypted media + metadata to Gateway',
    service: 'gateway',
    stage: 1,
    substage: 'upload',
    type: 'root',
    position: { x: 80, y: 10, z: 0 },
    children: ['node-2', 'node-3'],
    color: SERVICE_COLORS.gateway,
    estimatedTime: '~1s',
  },
  {
    id: 'node-2',
    name: 'Store to Walrus',
    icon: '💾',
    description: 'Gateway stores encrypted media to Walrus Storage',
    service: 'walrus',
    stage: 1,
    substage: 'store',
    type: 'service-call',
    position: { x: 50, y: 30, z: 0 },
    children: ['node-4'],
    color: SERVICE_COLORS.walrus,
    estimatedTime: '~2s',
  },
  {
    id: 'node-3',
    name: 'Submit to Queue',
    icon: '📋',
    description: 'Gateway submits verification job to Job Queue',
    service: 'queue',
    stage: 1,
    substage: 'queue',
    type: 'service-call',
    position: { x: 110, y: 30, z: 0 },
    children: ['node-4'],
    color: SERVICE_COLORS.queue,
    estimatedTime: '~0.5s',
  },
  {
    id: 'node-4',
    name: 'Queue Dispatch',
    icon: '🚀',
    description: 'Job Queue dispatches to 3 Nautilus Enclaves in parallel',
    service: 'queue',
    stage: 2,
    substage: 'dispatch',
    type: 'sequential',
    position: { x: 180, y: 10, z: 0 },
    children: ['node-5', 'node-13', 'node-21'],
    color: SERVICE_COLORS.queue,
    estimatedTime: '~0.5s',
  },

  // ===== STAGE 2: Enclave 1 Processing (8 nodes) =====
  {
    id: 'node-5',
    name: 'E1: Fetch Job',
    icon: '🎯',
    description: 'Enclave 1 fetches job from queue',
    service: 'queue',
    stage: 3,
    substage: 'e1-fetch',
    type: 'parallel',
    enclaveId: 1,
    position: { x: 280, y: 10, z: 0 },
    children: ['node-6'],
    color: SERVICE_COLORS.queue,
    estimatedTime: '~0.5s',
  },
  {
    id: 'node-6',
    name: 'E1: Request Key',
    icon: '🔑',
    description: 'Enclave 1 requests CEK/policy from Seal KMS',
    service: 'seal',
    stage: 4,
    substage: 'e1-key-req',
    type: 'service-call',
    enclaveId: 1,
    position: { x: 280, y: 25, z: 0 },
    children: ['node-7'],
    color: SERVICE_COLORS.seal,
    estimatedTime: '~1s',
  },
  {
    id: 'node-7',
    name: 'E1: Receive Key',
    icon: '✅',
    description: 'Seal KMS provides decryption key (attested) to Enclave 1',
    service: 'seal',
    stage: 4,
    substage: 'e1-key-recv',
    type: 'service-call',
    enclaveId: 1,
    position: { x: 280, y: 40, z: 0 },
    children: ['node-8'],
    color: SERVICE_COLORS.seal,
    estimatedTime: '~0.5s',
  },
  {
    id: 'node-8',
    name: 'E1: Fetch Media',
    icon: '📥',
    description: 'Enclave 1 fetches encrypted media from Walrus',
    service: 'walrus',
    stage: 4,
    substage: 'e1-fetch-media',
    type: 'service-call',
    enclaveId: 1,
    position: { x: 280, y: 55, z: 0 },
    children: ['node-9'],
    color: SERVICE_COLORS.walrus,
    estimatedTime: '~2s',
  },
  {
    id: 'node-9',
    name: 'E1: Reverse Search',
    icon: '🔍',
    description: 'Enclave 1 performs reverse search via APIs',
    service: 'reverse-search',
    stage: 4,
    substage: 'e1-reverse',
    type: 'service-call',
    enclaveId: 1,
    position: { x: 280, y: 70, z: 0 },
    children: ['node-10'],
    color: SERVICE_COLORS['reverse-search'],
    estimatedTime: '~5s',
  },
  {
    id: 'node-10',
    name: 'E1: AI Detection',
    icon: '🤖',
    description: 'Enclave 1 runs AI detection with 7 models + forensics',
    service: 'ai',
    stage: 4,
    substage: 'e1-ai',
    type: 'service-call',
    enclaveId: 1,
    position: { x: 280, y: 85, z: 0 },
    children: ['node-11'],
    color: SERVICE_COLORS.ai,
    estimatedTime: '~8s',
  },
  {
    id: 'node-11',
    name: 'E1: Upload Report',
    icon: '📤',
    description: 'Enclave 1 uploads signed report.json to Walrus',
    service: 'walrus',
    stage: 4,
    substage: 'e1-report',
    type: 'service-call',
    enclaveId: 1,
    position: { x: 280, y: 100, z: 0 },
    children: ['node-12'],
    color: SERVICE_COLORS.walrus,
    estimatedTime: '~1s',
  },
  {
    id: 'node-12',
    name: 'E1: Submit Attestation',
    icon: '⛓️',
    description: 'Enclave 1 submits attestation to Sui Blockchain',
    service: 'sui',
    stage: 4,
    substage: 'e1-attest',
    type: 'service-call',
    enclaveId: 1,
    position: { x: 280, y: 115, z: 0 },
    children: ['node-29'],
    color: SERVICE_COLORS.sui,
    estimatedTime: '~2s',
  },

  // ===== STAGE 3: Enclave 2 Processing (8 nodes, parallel) =====
  {
    id: 'node-13',
    name: 'E2: Fetch Job',
    icon: '🎯',
    description: 'Enclave 2 fetches job from queue',
    service: 'queue',
    stage: 3,
    substage: 'e2-fetch',
    type: 'parallel',
    enclaveId: 2,
    position: { x: 400, y: 10, z: 0 },
    children: ['node-14'],
    color: SERVICE_COLORS.queue,
    estimatedTime: '~0.5s',
  },
  {
    id: 'node-14',
    name: 'E2: Request Key',
    icon: '🔑',
    description: 'Enclave 2 requests CEK/policy from Seal KMS',
    service: 'seal',
    stage: 4,
    substage: 'e2-key-req',
    type: 'service-call',
    enclaveId: 2,
    position: { x: 400, y: 25, z: 0 },
    children: ['node-15'],
    color: SERVICE_COLORS.seal,
    estimatedTime: '~1s',
  },
  {
    id: 'node-15',
    name: 'E2: Receive Key',
    icon: '✅',
    description: 'Seal KMS provides decryption key (attested) to Enclave 2',
    service: 'seal',
    stage: 4,
    substage: 'e2-key-recv',
    type: 'service-call',
    enclaveId: 2,
    position: { x: 400, y: 40, z: 0 },
    children: ['node-16'],
    color: SERVICE_COLORS.seal,
    estimatedTime: '~0.5s',
  },
  {
    id: 'node-16',
    name: 'E2: Fetch Media',
    icon: '📥',
    description: 'Enclave 2 fetches encrypted media from Walrus',
    service: 'walrus',
    stage: 4,
    substage: 'e2-fetch-media',
    type: 'service-call',
    enclaveId: 2,
    position: { x: 400, y: 55, z: 0 },
    children: ['node-17'],
    color: SERVICE_COLORS.walrus,
    estimatedTime: '~2s',
  },
  {
    id: 'node-17',
    name: 'E2: Reverse Search',
    icon: '🔍',
    description: 'Enclave 2 performs reverse search via APIs',
    service: 'reverse-search',
    stage: 4,
    substage: 'e2-reverse',
    type: 'service-call',
    enclaveId: 2,
    position: { x: 400, y: 70, z: 0 },
    children: ['node-18'],
    color: SERVICE_COLORS['reverse-search'],
    estimatedTime: '~5s',
  },
  {
    id: 'node-18',
    name: 'E2: AI Detection',
    icon: '🤖',
    description: 'Enclave 2 runs AI detection with 7 models + forensics',
    service: 'ai',
    stage: 4,
    substage: 'e2-ai',
    type: 'service-call',
    enclaveId: 2,
    position: { x: 400, y: 85, z: 0 },
    children: ['node-19'],
    color: SERVICE_COLORS.ai,
    estimatedTime: '~8s',
  },
  {
    id: 'node-19',
    name: 'E2: Upload Report',
    icon: '📤',
    description: 'Enclave 2 uploads signed report.json to Walrus',
    service: 'walrus',
    stage: 4,
    substage: 'e2-report',
    type: 'service-call',
    enclaveId: 2,
    position: { x: 400, y: 100, z: 0 },
    children: ['node-20'],
    color: SERVICE_COLORS.walrus,
    estimatedTime: '~1s',
  },
  {
    id: 'node-20',
    name: 'E2: Submit Attestation',
    icon: '⛓️',
    description: 'Enclave 2 submits attestation to Sui Blockchain',
    service: 'sui',
    stage: 4,
    substage: 'e2-attest',
    type: 'service-call',
    enclaveId: 2,
    position: { x: 400, y: 115, z: 0 },
    children: ['node-29'],
    color: SERVICE_COLORS.sui,
    estimatedTime: '~2s',
  },

  // ===== STAGE 4: Enclave 3 Processing (8 nodes, parallel) =====
  {
    id: 'node-21',
    name: 'E3: Fetch Job',
    icon: '🎯',
    description: 'Enclave 3 fetches job from queue',
    service: 'queue',
    stage: 3,
    substage: 'e3-fetch',
    type: 'parallel',
    enclaveId: 3,
    position: { x: 520, y: 10, z: 0 },
    children: ['node-22'],
    color: SERVICE_COLORS.queue,
    estimatedTime: '~0.5s',
  },
  {
    id: 'node-22',
    name: 'E3: Request Key',
    icon: '🔑',
    description: 'Enclave 3 requests CEK/policy from Seal KMS',
    service: 'seal',
    stage: 4,
    substage: 'e3-key-req',
    type: 'service-call',
    enclaveId: 3,
    position: { x: 520, y: 25, z: 0 },
    children: ['node-23'],
    color: SERVICE_COLORS.seal,
    estimatedTime: '~1s',
  },
  {
    id: 'node-23',
    name: 'E3: Receive Key',
    icon: '✅',
    description: 'Seal KMS provides decryption key (attested) to Enclave 3',
    service: 'seal',
    stage: 4,
    substage: 'e3-key-recv',
    type: 'service-call',
    enclaveId: 3,
    position: { x: 520, y: 40, z: 0 },
    children: ['node-24'],
    color: SERVICE_COLORS.seal,
    estimatedTime: '~0.5s',
  },
  {
    id: 'node-24',
    name: 'E3: Fetch Media',
    icon: '📥',
    description: 'Enclave 3 fetches encrypted media from Walrus',
    service: 'walrus',
    stage: 4,
    substage: 'e3-fetch-media',
    type: 'service-call',
    enclaveId: 3,
    position: { x: 520, y: 55, z: 0 },
    children: ['node-25'],
    color: SERVICE_COLORS.walrus,
    estimatedTime: '~2s',
  },
  {
    id: 'node-25',
    name: 'E3: Reverse Search',
    icon: '🔍',
    description: 'Enclave 3 performs reverse search via APIs',
    service: 'reverse-search',
    stage: 4,
    substage: 'e3-reverse',
    type: 'service-call',
    enclaveId: 3,
    position: { x: 520, y: 70, z: 0 },
    children: ['node-26'],
    color: SERVICE_COLORS['reverse-search'],
    estimatedTime: '~5s',
  },
  {
    id: 'node-26',
    name: 'E3: AI Detection',
    icon: '🤖',
    description: 'Enclave 3 runs AI detection with 7 models + forensics',
    service: 'ai',
    stage: 4,
    substage: 'e3-ai',
    type: 'service-call',
    enclaveId: 3,
    position: { x: 520, y: 85, z: 0 },
    children: ['node-27'],
    color: SERVICE_COLORS.ai,
    estimatedTime: '~8s',
  },
  {
    id: 'node-27',
    name: 'E3: Upload Report',
    icon: '📤',
    description: 'Enclave 3 uploads signed report.json to Walrus',
    service: 'walrus',
    stage: 4,
    substage: 'e3-report',
    type: 'service-call',
    enclaveId: 3,
    position: { x: 520, y: 100, z: 0 },
    children: ['node-28'],
    color: SERVICE_COLORS.walrus,
    estimatedTime: '~1s',
  },
  {
    id: 'node-28',
    name: 'E3: Submit Attestation',
    icon: '⛓️',
    description: 'Enclave 3 submits attestation to Sui Blockchain',
    service: 'sui',
    stage: 4,
    substage: 'e3-attest',
    type: 'service-call',
    enclaveId: 3,
    position: { x: 520, y: 115, z: 0 },
    children: ['node-29'],
    color: SERVICE_COLORS.sui,
    estimatedTime: '~2s',
  },

  // ===== STAGE 5: Aggregation & Consensus (5 nodes) =====
  {
    id: 'node-29',
    name: 'Collect Reports',
    icon: '🔄',
    description: 'Aggregator collects reports from E1, E2, E3',
    service: 'aggregator',
    stage: 5,
    substage: 'aggregate',
    type: 'merge',
    position: { x: 640, y: 60, z: 0 },
    children: ['node-30'],
    color: SERVICE_COLORS.aggregator,
    estimatedTime: '~1s',
  },
  {
    id: 'node-30',
    name: 'Publish Consensus',
    icon: '✅',
    description: 'Aggregator publishes final consensus to Sui',
    service: 'sui',
    stage: 5,
    substage: 'consensus',
    type: 'sequential',
    position: { x: 700, y: 60, z: 0 },
    children: ['node-31'],
    color: SERVICE_COLORS.sui,
    estimatedTime: '~2s',
  },
  {
    id: 'node-31',
    name: 'Emit Event',
    icon: '📡',
    description: 'Sui emits event for dashboard/frontend',
    service: 'sui',
    stage: 6,
    substage: 'emit',
    type: 'sequential',
    position: { x: 760, y: 60, z: 0 },
    children: ['node-32'],
    color: SERVICE_COLORS.sui,
    estimatedTime: '~0.5s',
  },
  {
    id: 'node-32',
    name: 'UI Receives Event',
    icon: '🎨',
    description: 'Frontend receives event from Sui',
    service: undefined,
    stage: 6,
    substage: 'ui-event',
    type: 'sequential',
    position: { x: 820, y: 60, z: 0 },
    children: ['node-33'],
    color: SERVICE_COLORS.gateway,
    estimatedTime: '~0.1s',
  },
  {
    id: 'node-33',
    name: 'Fetch Final Report',
    icon: '📥',
    description: 'UI fetches report.json from Walrus for display',
    service: 'walrus',
    stage: 6,
    substage: 'fetch-report',
    type: 'sequential',
    position: { x: 850, y: 60, z: 0 },
    children: [],
    color: SERVICE_COLORS.walrus,
    estimatedTime: '~1s',
  },
];

// Generate connections based on parent-child relationships
export const TREE_CONNECTIONS: TreeConnection[] = TREE_NODES.flatMap((node) =>
  node.children.map((childId) => {
    const child = TREE_NODES.find((n) => n.id === childId);
    if (!child) return null;

    // Determine connection type based on positions
    let type: 'vertical' | 'horizontal' | 'diagonal' = 'vertical';
    
    if (Math.abs(node.position.x - child.position.x) > 15) {
      type = 'diagonal';
    } else if (Math.abs(node.position.y - child.position.y) < 5) {
      type = 'horizontal';
    }

    return {
      id: `conn-${node.id}-${childId}`,
      from: node.id,
      to: childId,
      type,
    };
  })
).filter(Boolean) as TreeConnection[];

